CREATE TABLE STG_RETAIL_TRANSACTIONS
(
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    invoice_no      VARCHAR2(20),
    stock_code      VARCHAR2(50),
    description     VARCHAR2(500),
    quantity        NUMBER,
    invoice_date    DATE,
    unit_price      NUMBER(10,2),
    customer_id     NUMBER,
    country         VARCHAR2(100),

    load_date       DATE DEFAULT SYSDATE,
    source_file     VARCHAR2(200)
);