CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(150) NOT NULL,
    customer_type VARCHAR2(30),
    industry VARCHAR2(100),
    email VARCHAR2(150),
    phone VARCHAR2(30),
    credit_limit NUMBER(12,2),
    current_balance NUMBER(12,2) DEFAULT 0,
    risk_category VARCHAR2(20),
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_customers
        PRIMARY KEY (customer_id),

    CONSTRAINT chk_customer_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),

    CONSTRAINT chk_risk_category
        CHECK (risk_category IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE payment_terms (
    payment_term_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    term_name       VARCHAR2(50) NOT NULL,
    due_days        NUMBER NOT NULL,
    description     VARCHAR2(200),

    CONSTRAINT pk_payment_terms
        PRIMARY KEY (payment_term_id),

    CONSTRAINT uq_payment_term_name
        UNIQUE (term_name),

    CONSTRAINT chk_due_days
        CHECK (due_days > 0)
);