CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(150) NOT NULL,
    customer_type VARCHAR2(30),
    industry VARCHAR2(100),
    email VARCHAR2(150),
    phone VARCHAR2(30),
    credit_limit NUMBER(12,2),
    current_balance NUMBER(12,2) DEFAULT 0,
    risk_category VARCHAR2(20),
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_customers
        PRIMARY KEY (customer_id),

    CONSTRAINT chk_customer_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),

    CONSTRAINT chk_risk_category
        CHECK (risk_category IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE payment_terms (
    payment_term_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    term_name       VARCHAR2(50) NOT NULL,
    due_days        NUMBER NOT NULL,
    description     VARCHAR2(200),

    CONSTRAINT pk_payment_terms
        PRIMARY KEY (payment_term_id),

    CONSTRAINT uq_payment_term_name
        UNIQUE (term_name),

    CONSTRAINT chk_due_days
        CHECK (due_days > 0)
);

CREATE TABLE invoices (
    invoice_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    invoice_number      VARCHAR2(50) NOT NULL,
    customer_id         NUMBER NOT NULL,
    payment_term_id     NUMBER NOT NULL,
    invoice_date        DATE NOT NULL,
    due_date            DATE NOT NULL,
    invoice_amount      NUMBER(12,2) NOT NULL,
    amount_paid         NUMBER(12,2) DEFAULT 0,
    outstanding_amount  NUMBER(12,2) DEFAULT 0,
    invoice_status      VARCHAR2(30) DEFAULT 'OPEN',
    dispute_flag        CHAR(1) DEFAULT 'N',
    created_date        DATE DEFAULT SYSDATE,

    CONSTRAINT pk_invoices
        PRIMARY KEY (invoice_id),

    CONSTRAINT uq_invoice_number
        UNIQUE (invoice_number),

    CONSTRAINT fk_invoice_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_invoice_payment_term
        FOREIGN KEY (payment_term_id)
        REFERENCES payment_terms(payment_term_id),

    CONSTRAINT chk_invoice_status
        CHECK (
            invoice_status IN
            ('OPEN','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED')
        ),

    CONSTRAINT chk_dispute_flag
        CHECK (dispute_flag IN ('Y','N'))
);

CREATE TABLE invoice_lines (
    invoice_line_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    invoice_id      NUMBER NOT NULL,
    product_code    VARCHAR2(50),
    description     VARCHAR2(200),
    quantity        NUMBER NOT NULL,
    unit_price      NUMBER(12,2) NOT NULL,
    line_amount     NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_invoice_lines
        PRIMARY KEY (invoice_line_id),

    CONSTRAINT fk_invoice_line_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoices(invoice_id),

    CONSTRAINT chk_invoice_line_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_invoice_line_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_invoice_line_amount
        CHECK (line_amount >= 0)
);

CREATE TABLE payments (
    payment_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    invoice_id        NUMBER NOT NULL,
    payment_date      DATE NOT NULL,
    payment_amount    NUMBER(12,2) NOT NULL,
    payment_method    VARCHAR2(30),
    reference_number  VARCHAR2(100),
    created_date      DATE DEFAULT SYSDATE,

    CONSTRAINT pk_payments
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoices(invoice_id),

    CONSTRAINT chk_payment_amount
        CHECK (payment_amount > 0)
);