/*==============================================================
  ORACLE AI AR AGENT AUDIT TABLES
==============================================================*/

CREATE TABLE agent_conversations
(
    conversation_id     VARCHAR2(36)   NOT NULL,
    started_at          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ended_at            TIMESTAMP,
    conversation_status VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    created_by          VARCHAR2(100)  DEFAULT USER NOT NULL,

    CONSTRAINT pk_agent_conversations
        PRIMARY KEY (conversation_id),

    CONSTRAINT chk_agent_conversation_status
        CHECK (
            conversation_status IN (
                'ACTIVE',
                'COMPLETED',
                'ERROR'
            )
        )
);


CREATE TABLE agent_activity_log
(
    activity_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    conversation_id   VARCHAR2(36)  NOT NULL,
    activity_time     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    activity_type     VARCHAR2(30)  NOT NULL,

    user_question     VARCHAR2(4000),
    tool_name         VARCHAR2(100),
    tool_arguments    CLOB,
    records_returned  NUMBER,
    agent_response    CLOB,

    execution_status  VARCHAR2(20) DEFAULT 'SUCCESS' NOT NULL,
    error_message     VARCHAR2(4000),

    CONSTRAINT pk_agent_activity_log
        PRIMARY KEY (activity_id),

    CONSTRAINT fk_agent_activity_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES agent_conversations(conversation_id),

    CONSTRAINT chk_agent_activity_type
        CHECK (
            activity_type IN (
                'USER_MESSAGE',
                'TOOL_CALL',
                'AGENT_RESPONSE',
                'ERROR',
                'MEMORY_CLEAR',
                'SESSION_END'
            )
        ),

    CONSTRAINT chk_agent_execution_status
        CHECK (
            execution_status IN (
                'SUCCESS',
                'FAILED'
            )
        )
);


CREATE INDEX idx_agent_activity_conversation
    ON agent_activity_log
    (
        conversation_id,
        activity_time
    );