/*==============================================================
  AGENT APPROVAL WORKFLOW
==============================================================*/

CREATE TABLE agent_approval_requests
(
    approval_id          NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    conversation_id      VARCHAR2(36)   NOT NULL,
    requested_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    requested_by         VARCHAR2(100)  DEFAULT USER NOT NULL,

    action_type          VARCHAR2(50)   NOT NULL,
    action_description   VARCHAR2(1000) NOT NULL,
    action_payload       CLOB,

    approval_status      VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,

    reviewed_at          TIMESTAMP,
    reviewed_by          VARCHAR2(100),
    review_comments      VARCHAR2(1000),

    executed_at          TIMESTAMP,
    execution_status     VARCHAR2(20),
    execution_message    VARCHAR2(1000),

    CONSTRAINT pk_agent_approval_requests
        PRIMARY KEY (approval_id),

    CONSTRAINT fk_agent_approval_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES agent_conversations(conversation_id),

    CONSTRAINT chk_agent_approval_status
        CHECK (
            approval_status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'EXECUTED'
            )
        ),

    CONSTRAINT chk_agent_approval_exec_status
        CHECK (
            execution_status IS NULL
            OR execution_status IN (
                'SUCCESS',
                'FAILED'
            )
        )
);


CREATE INDEX idx_agent_approval_status
    ON agent_approval_requests
    (
        approval_status,
        requested_at
    );
