/*==============================================================
  DAY 16: APPROVED NOTIFICATION OUTBOX
==============================================================*/

CREATE TABLE agent_notification_outbox
(
    notification_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    approval_id          NUMBER         NOT NULL,
    conversation_id      VARCHAR2(36)   NOT NULL,

    notification_type    VARCHAR2(50)   NOT NULL,

    recipient_address    VARCHAR2(320),
    subject_text         VARCHAR2(500),
    message_body         CLOB,

    notification_status  VARCHAR2(20)
        DEFAULT 'PENDING' NOT NULL,

    retry_count          NUMBER
        DEFAULT 0 NOT NULL,

    created_at           TIMESTAMP
        DEFAULT SYSTIMESTAMP NOT NULL,

    processed_at         TIMESTAMP,

    error_message        VARCHAR2(4000),

    CONSTRAINT pk_agent_notification_outbox
        PRIMARY KEY (notification_id),

    CONSTRAINT fk_outbox_approval
        FOREIGN KEY (approval_id)
        REFERENCES agent_approval_requests(approval_id),

    CONSTRAINT fk_outbox_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES agent_conversations(conversation_id),

    CONSTRAINT uq_outbox_approval
        UNIQUE (approval_id),

    CONSTRAINT chk_notification_status
        CHECK (
            notification_status IN (
                'PENDING',
                'PROCESSING',
                'SENT',
                'FAILED'
            )
        )
);


CREATE INDEX idx_notification_outbox_status
    ON agent_notification_outbox
    (
        notification_status,
        created_at
    );

commit;