/* ============================================================
   NOTIFICATION RECOVERY + REQUEUE AUDIT
   ============================================================ */


/* ============================================================
   CREATE RECOVERY AUDIT TABLE
   ============================================================ */

CREATE TABLE agent_notification_recovery_log
(
    recovery_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    notification_id NUMBER NOT NULL,

    previous_status VARCHAR2(20) NOT NULL,

    new_status VARCHAR2(20) NOT NULL,

    recovered_by VARCHAR2(100) NOT NULL,

    recovery_reason VARCHAR2(1000),

    recovered_at TIMESTAMP
        DEFAULT SYSTIMESTAMP
        NOT NULL,

    CONSTRAINT pk_notification_recovery_log
        PRIMARY KEY (recovery_id),

    CONSTRAINT fk_recovery_notification
        FOREIGN KEY (notification_id)
        REFERENCES agent_notification_outbox
        (notification_id),

    CONSTRAINT chk_recovery_status
        CHECK
        (
            previous_status IN
            (
                'DEAD',
                'FAILED',
                'RETRY'
            )
            AND
            new_status IN
            (
                'PENDING'
            )
        )
);


/* ============================================================
   INDEX FOR RECOVERY HISTORY
   ============================================================ */

CREATE INDEX idx_notification_recovery
ON agent_notification_recovery_log
(
    notification_id,
    recovered_at
);


/* ============================================================
   VERIFY DEAD NOTIFICATIONS
   ============================================================ */

SELECT
    notification_id,
    approval_id,
    notification_type,
    recipient_address,
    notification_status,
    retry_count,
    max_retry_count,
    failure_reason,
    error_message,
    dead_at
FROM agent_notification_outbox
WHERE notification_status = 'DEAD'
ORDER BY dead_at;


/* ============================================================
   VERIFY RECOVERY LOG
   ============================================================ */

SELECT
    recovery_id,
    notification_id,
    previous_status,
    new_status,
    recovered_by,
    recovery_reason,
    recovered_at
FROM agent_notification_recovery_log
ORDER BY recovery_id;


COMMIT;