/* ============================================================
   END-TO-END ACTION ORCHESTRATION AUDIT
   ============================================================ */


/* ============================================================
   CREATE ORCHESTRATION AUDIT TABLE
   ============================================================ */

CREATE TABLE agent_orchestration_runs
(
    orchestration_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    invoice_number VARCHAR2(100)
        NOT NULL,

    approval_id NUMBER,

    notification_id NUMBER,

    orchestration_status VARCHAR2(30)
        DEFAULT 'STARTED'
        NOT NULL,

    current_step VARCHAR2(100),

    started_at TIMESTAMP
        DEFAULT SYSTIMESTAMP
        NOT NULL,

    completed_at TIMESTAMP,

    error_message VARCHAR2(4000),

    CONSTRAINT pk_agent_orchestration_runs
        PRIMARY KEY (orchestration_id),

    CONSTRAINT fk_orchestration_approval
        FOREIGN KEY (approval_id)
        REFERENCES agent_approval_requests
        (approval_id),

    CONSTRAINT fk_orchestration_notification
        FOREIGN KEY (notification_id)
        REFERENCES agent_notification_outbox
        (notification_id),

    CONSTRAINT chk_orchestration_status
        CHECK
        (
            orchestration_status IN
            (
                'STARTED',
                'WAITING_APPROVAL',
                'APPROVED',
                'QUEUED',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        )
);


/* ============================================================
   INDEX FOR ORCHESTRATION HISTORY
   ============================================================ */

CREATE INDEX idx_orchestration_status
ON agent_orchestration_runs
(
    orchestration_status,
    started_at
);


/* ============================================================
   INDEX FOR INVOICE LOOKUP
   ============================================================ */

CREATE INDEX idx_orchestration_invoice
ON agent_orchestration_runs
(
    invoice_number
);


/* ============================================================
   VERIFY TABLE
   ============================================================ */

SELECT
    orchestration_id,
    invoice_number,
    approval_id,
    notification_id,
    orchestration_status,
    current_step,
    started_at,
    completed_at,
    error_message
FROM agent_orchestration_runs
ORDER BY orchestration_id;


/* ============================================================
   ORCHESTRATION STATUS SUMMARY
   ============================================================ */

SELECT
    orchestration_status,
    COUNT(*) AS run_count
FROM agent_orchestration_runs
GROUP BY orchestration_status
ORDER BY orchestration_status;


COMMIT;